### ISSUE TITLE
Allowing strings as objects to properties

### ISSUE THREAD

**Issue by kcoyle** [dcmi/openwemi#46]
Legend:

```mermaid
flowchart LR
O((object)) --> T[text]
```

What we have now defines links between two objects. (I'm using Work and Expression here to illustrate this, but it is true for all.)

```mermaid
flowchart LR
E((Expression)) --> |expresses| W((Work))
```

Let's say that you have a book in translation, and the following information in your data store:

--URI:Book3--
Title: "War and Peace"
Original work: URI:Tolstoj1

This meets the current definition of the openWEMI vocabulary. But what if your database does not have a URI for the work, because you do not have that version in your database. But you might have information about the original title is a text. 

--URI:Book3--
Title: "War and Peace"
Original work: "Война и мир"

 You may want to use the openWEMI property of `expresses` even though you do not have a URI for the work:

```mermaid
flowchart LR
E((Book3)) --> |expresses| W[Война и мир]
```
As the vocabulary is defined today, this requires the use of a blank node:
```mermaid
flowchart LR
E((Book3)) --> |expresses|B((work bnode)) --> |work title| W[Война и мир]
```
For the inverse properties that we have proposed, the situation is similar. If defined with ranges, such as:

``<http://example.org/openWEMI/expressedBy>``
``  a owl:ObjectProperty ;``
``  rdfs:label "expressedBy"@en ;``
``  skos:definition "A Work that is expressed by an Expression"@en ;``
``  rdfs:isDefinedBy <http://example.org/openWEMI/> ;``
``  rdfs:subPropertyOf <http://example.org/openWEMI/relatedEndeavor> ;``
``  rdfs:domain <http://example.org/openWEMI/Work> ;``
``  rdfs:range <http://example.org/openWEMI/Expression>  .``
Which looks like:
```mermaid
flowchart LR
W((Work)) --> |expressedBy|B((Expression))
```
However, the inverse `expressedBy` is useful even when the `Expression` is not identified with a URI:

```mermaid
flowchart LR
W((Work)) --> |expressedBy|B["Session 1"]
```
Again, if the property is defined with a range of `Expression` it will be necessary to use a bnode as the object of `expressedBy` so that a text string can represent the Expression.

```mermaid
flowchart LR
W((Work)) --> |expressedBy|B((Expression bnode)) --> |expression| E[Session 1]
```

**Comment by kcoyle** [comment]
One possible solution is to use [`rangeIncludes`](https://schema.org/rangeIncludes) as defined in schema.org. This is defined as:
> Relates a property to a class that constitutes (one of) the expected type(s) for values of the property.

To include the possibility of texts, schema has defined a class `Text`, and makes statements like:
>     :rangeIncludes :Text ;

Note that many of the schema.org properties do not include `sdo:Text `in the `rangeIncludes` statement, so not all properties are defined as including a text object.

**Comment by seanpetiya** [comment]
I believe the scenario described here would be similar to not having a URI for an agent (person, company, etc.). For example, a dataset of books, but with limited or no authority data for authors (especially for self-published or crowd-funded materials). The creators of that dataset may choose to create RDF statements (`schema:author`, `dct:creator`, etc.) with literal values instead of URIs (e.g. `ex:Book schema:author "Herman Melville"` vs. `ex:Book schema:author ex:HermanMelville` or `ex:Book schema:author http://id.loc.gov/authorities/names/n79006936`). This of course violates the "expected type" [1] or range [2] defined by the vocabulary, but not RDF (the object of our triple in this statement can still be a literal or a URI [3]).

However, best practice is probably to create a blank node, if for no other reason than to satisfy a validator. The same would probably be true where we have the title of an expression, but no valid URI. We could "mint" our own URI (e.g. `ex:HermanMelville`) or create the blank node, allowing the graph for this work to then be expanded upon through links to other datasets (perhaps another dataset contains a URI for this expression, or will provide one in the future?).

To formalize that both implementations are acceptable from the perspective of openWEMI, I think incorporating  `schema:rangeIncludes` would be a good solution, especially in addition to `rdfs:range`.

[1] https://schema.org/author
[2] https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/creator
[3] https://www.w3.org/TR/2023/WD-rdf12-concepts-20230516/#section-triples

**Comment by kcoyle** [comment]
Decision in June 14 meeting: properties will have ranges. This means that the properties will have IRIs or bnodes in the object position of the triple. Documentation will explain the implications of using strings as objects.
