### ISSUE TITLE
Why "openWEMI" and not "OpenWEMI"?

### ISSUE THREAD

**Issue by tombaker** [dcmi/openwemi#86]
To me, OpenWEMI (title case) seems more natural than openWEMI (lowercase), especially if it were to appear at the start of a sentence.

**Comment by kcoyle** [comment]
I'm "open" to whatever people find most expressive, but I personally hate camel case because I find it hard to hit the shift key in the middle of a word, so I'd lean toward "openwemi" as the easiest to type. We have opted for "openwemi" as the prefix in our examples, for that reason. The documentation, of course, could use a different case.

**Comment by tombaker** [comment]
FWIW, I think `openwemi` is fine as a prefix (not too long, in my opinion). However, no other DCMI specifications start with lowercase, and "Openwemi" doesn't look right. To me, "OpenWEMI" would look the most natural as the name of the specification and, I think, most in line with current practice. Am open to counter-examples and counter-arguments.

**Comment by philbarker** [comment]
If changing/normalizing it is on the cards, OpenWEMI as the official name would get my vote (I am rubbish at typing even in lower case, so don't notice much difference with CamelCase and the like).

**Comment by kcoyle** [comment]
Agreed. I will edit the documents, after which I will close this.

**Comment by kcoyle** [comment]
done.
