### ISSUE TITLE
Examples that are "consistent" (or not) with the OpenWEMI data model

### ISSUE THREAD

**Issue by tombaker** [dcmi/openwemi#93]
The [SKOS Reference specification](https://www.w3.org/TR/skos-reference/) provided concise examples of things that were "consistent" or "not consistent" with the SKOS data model (see below).

The OpenWEMI documentation could perhaps do something similar, not just for relations between OpenWEMI entities but also, potentially, for relations between OpenWEMI entities and other FRBR-like models (eg, FRBR-LRM, BIBFRAME).

![skos_reference](https://github.com/dcmi/openwemi/assets/1106086/eaf7d70f-2f44-459b-85ba-7c167b2f2b1f)

**Comment by kcoyle** [comment]
@tombaker I suppose we could do something like this in the cookbook. I think it would be too messy for the primer because there are a lot of relationships that are one-to-many and those are hard to show. So Item can instantiate a Work, an Expression, or a Manifestation, but W-M-E cannot instantiate an item. Maybe what we need more is a clearer description of the concept of levels of abstraction that flow from Work to Item. If that is clear then the directionality of the properties (their ranges) may have more emphasis in the documentation.

**Comment by kcoyle** [comment]
March 27 meeting, group doesn't want to do this. There are few things you could do that are inconsistent. That's what "open" is about.
